### ISSUE TITLE
easy-ViTPose Import error

### ISSUE THREAD

**Issue by fab0822** [JunkyByte/easy_ViTPose#11]
Hi, thank you for providing this simple implementation of ViTPose! 
Two weeks ago I was running the code in Google Colab, but when I tried to run it again today, I encountered an error while trying to install the easy_ViTPose package.
The error message I received was as follows:

```
Obtaining file:///content/easy_ViTPose
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```  

How can I solve this problem?

**Comment by JunkyByte** [comment]
Thanks! there was a syntax error in last commit!
It should work now

**Comment by fab0822** [comment]
Thanks for the quick response! It is working now!
