### ISSUE TITLE
No module named 'configs'

### ISSUE THREAD

**Issue by duchao11280** [JunkyByte/easy_ViTPose#16]
Hi, i have some problems when clone easy_ViTPose and `pip install -e . `
Please help or fix that.
Thanks regards
![image](https://github.com/JunkyByte/easy_ViTPose/assets/30766129/694b3dff-c1f4-43d2-9ffe-fc353df2ca19)

**Comment by JunkyByte** [comment]
Hello, thanks! should work now, pull last commit. I introduced a discrepancy with relative and absolute import from previous changes.

lmk if it works for you

**Comment by duchao11280** [comment]
It works, thank you so much.
