### ISSUE TITLE
error when i use .engine files to use tensorrt

### ISSUE THREAD

**Issue by chethanreddy1** [JunkyByte/easy_ViTPose#20]
![image](https://github.com/JunkyByte/easy_ViTPose/assets/95535293/eb5db08d-3e99-4486-b3da-66edf0e1916c)

**Comment by JunkyByte** [comment]
Have you generated the .engine checkpoints by yourself? I had a similar problem with recent versions of trt. But I would start by trying to generate the checkpoints by yourself

**Comment by chethanreddy1** [comment]
no, i downloaded the checkpoints from Hugging Face, but when I try to generate the checkpoint by myself using your to_trt.ipynb file the model is not defined in third cell
![Uploading image.png…]()

**Comment by JunkyByte** [comment]
Use the export.py script

**Comment by chethanreddy1** [comment]
yeah it works

**Comment by chethanreddy1** [comment]
works !
