### ISSUE TITLE
Error with tensorrt model

### ISSUE THREAD

**Issue by carolinelgrd** [JunkyByte/easy_ViTPose#21]
Hi,
Thank you for the work you've done.
I have run the inference script with the torch model (vit-pose-coco-s) on my webcam using a gpu and it worked well.
After that I tried to use the tensorrt model provided and I converted the yolov8.pt file to a engine file. When running the script, I'm having this error:
[TRT] [E] 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
trt_engine is empty (None)
Traceback (most recent call last):
  File "C:\Users\tech\Desktop\Caroline\Internship_Project\Internship_Project\VitPose\easy_ViTPose\testinf.py", line 45, in <module>
    model = VitInference(model_path, yolo_path, model_name='s', yolo_size=640, is_video=True, device="cuda")
  File "C:\Users\tech\Desktop\Caroline\Internship_Project\Internship_Project\VitPose\easy_ViTPose\easy_ViTPose\inference.py", line 169, in __init__
    engine_utils.allocate_buffers(trt_engine)
  File "C:\Users\tech\Desktop\Caroline\Internship_Project\Internship_Project\VitPose\easy_ViTPose\easy_ViTPose\utils_engine.py", line 98, in allocate_buffers
    for binding in engine:
TypeError: 'NoneType' object is not iterable

The loading function return an empty engine. 

Thank you.

**Comment by JunkyByte** [comment]
Hello, the tensorrt versions are giving some headaches and I will find the time to work on them a bit.
Could you tell me the tensorrt / cuda version you have installed?

Have you generated the tensorrt checkpoint by yourself or downloaded one from hugging face?

**Comment by carolinelgrd** [comment]
Thanks for reply!
I'm using cuda12.1, TensorRT-8.6.1.6 and cudnn 8.9.0
I have downloaded the files from hugging face.

**Comment by JunkyByte** [comment]
Thanks, seems the same as https://github.com/JunkyByte/easy_ViTPose/issues/20, try to generate the checkpoints by yourself using `export.py` and report back. I will probably delete the tensorrt ckpts from hf, they only work on same configuration it seems to me.

**Comment by carolinelgrd** [comment]
I already tried to use the export.py file but the torch.onnx.export function doesn't seem to function. The program stop after this command and no file is created. 
I tried to reinstall the requirement.txt but it doesn't worked.

**Comment by JunkyByte** [comment]
Do you get any error or output when running `export.py`? What command are you using to run it?

**Comment by carolinelgrd** [comment]
I'm using torch 2.1.0+cu121, onnxruntime 1.16.0 and onnxruntime-gpu 1.16.0. Yes I have the gpu version for torch.

**Comment by JunkyByte** [comment]
Do you have both the onnxruntime installed? It seems from documentation you should only have one installed at any time. Could you try uninstalling both and reinstalling just the gpu version?


As soon as I have the time I will check on my main pc which has an nvidia gpu which versions I am using and report back. If I can't reproduce the problem I might have trouble helping.

**Comment by carolinelgrd** [comment]
I had both installed but I've just uninstalled both and installed the gpu version but I still have the same problem.
I have a Nvidia GTX 1650 Ti GPU. Thank you for your help.

**Comment by JunkyByte** [comment]
Could you try to rerun with verbose=True in the function call and also output in local path (change the third argument of the export to something like 'test.onnx')? (Change the src) I wonder if it will give any message.

I would also try to export following the torch example, just to be sure you are able to run a minimal example and this is a problem with the repo https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

Thanks.

**Comment by carolinelgrd** [comment]
I've tried what you said but it doesn't work.
I tried the pytorch example and it works fine the file is created.

**Comment by JunkyByte** [comment]
Does the verbose=True version outputs anything? It should provide the list of layers it is iterating on to construct the onnx version

**Comment by carolinelgrd** [comment]
The verbose True doesn't output anything but with the pytorch example it outputs something.

**Comment by JunkyByte** [comment]
Hello, sorry I had a busy weekend, I did not manage to make the tensorrt work on cuda-12.
But with cuda 12.1, your onnxruntime-gpu version if I use `export.py` it works okay, outputting both the .engine and the .onnx.
Currently I have the following working version on Ubuntu (both models on tensorrt using default yolo export and my export.py):
```
Driver Version: 535.104.12   CUDA Version: 11.8   GTX1080Ti
pip version:
torch                        2.1.0+cu118
torchaudio                   2.1.0+cu118
torchmetrics                 0.11.1
torchvision                  0.16.0+cu118
tensorrt                     8.6.1
onnx                         1.14.1
onnx-simplifier              0.4.28
onnxruntime-gpu              1.16.1
```


I'm sorry but I don't really know how to help you :)

**Comment by JunkyByte** [comment]
Hello, I now use torch_tensorrt for exporting. if you are still using this you can test if tensorrt export works for you now. Feel free to reopen the issue.
