### ISSUE TITLE
Shoulder joint

### ISSUE THREAD

**Issue by sourenpash** [JunkyByte/easy_ViTPose#22]
Hello, 

Im having a hard time finding out which keypoint is the shoulder for my model and was hoping someone knows. 

`import os
import math
import numpy as np
import pandas as pd
from easy_ViTPose import VitInference
import cv2
from tqdm import tqdm
from math import atan2, degrees

print("Initializing model...")
model_path = './vitpose-25-s.pth'
yolo_path = './yolov5s.onnx'
model = VitInference(model_path, yolo_path, model_name='s', yolo_size=320, is_video=False, device=None)
`

**Comment by JunkyByte** [comment]
Hello, you can find the skeletons for your model here: [easy_ViTPose/easy_ViTPose/vit_utils/visualization.py](https://github.com/JunkyByte/easy_ViTPose/blob/b6d98158abc6996463db0d613182f59cbc519150/easy_ViTPose/vit_utils/visualization.py#L13)

**Comment by sourenpash** [comment]
yeah Iv been looking in that I think for my model its 6, and 7 but I'm trying to verify and I'm getting this line drawn for it. 
![image](https://github.com/JunkyByte/easy_ViTPose/assets/111321387/8685a512-05ec-45fc-a681-0dd05eca3d04)

**Comment by JunkyByte** [comment]
Please provide the code you used for this result and the image, you should also convert the image to RGB before inference or back to BGR if you are using cv2 for showing it.

```python
img = cv2.imread('img.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
model.inference(img)

img = model.draw(show_yolo=True, show_raw_yolo=True, confidence_threshold=0.2)  # Returns RGB image with drawings
cv2.imshow('image', cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
cv2.waitKey(0)
```

**Comment by sourenpash** [comment]
hey thank you so much for the help, yeah I realized the way I'm showing is messed up but Iv just been trying to figure out the joints so been ignoring it. 

the code is very short I'll put it here. all I'm trying to do is create a line from one shoulder to the other. 

`import os
import math
import numpy as np
import pandas as pd
from easy_ViTPose import VitInference
import cv2
from tqdm import tqdm
from math import atan2, degrees

# Initialize the model
print("Initializing model...")
model_path = './vitpose-25-s.pth'
yolo_path = './yolov5s.onnx'
model = VitInference(model_path, yolo_path, model_name='s', yolo_size=320, is_video=False, device=None)

# Constants
frames_root_directory = 'testFrames'
robot_coords = np.array([355, 287])
sink_coords = np.array([234, 275])
radius_sink = 200
radius_robot = 200


near_sink_or_robot_dict = {}
df_data = []

def draw_line(frame, point1, point2, color, thickness):
    cv2.line(frame, tuple(point1.astype(int)), tuple(point2.astype(int)), color, thickness)

def is_facing_robot(frame, keypoints, angle_tolerance=10):

    left_shoulder_person = keypoints[5, :2]
    right_shoulder_person = keypoints[6, :2]

    # Calculate slope for person's shoulder line
    dy_person = left_shoulder_person[1] - right_shoulder_person[1]
    dx_person = left_shoulder_person[0] - right_shoulder_person[0]
    slope_person = atan2(dy_person, dx_person)

    # Constants for robot's shoulder keypoints
    left_shoulder_robot = np.array([339, 188])
    right_shoulder_robot = np.array([362, 188])

    # Calculate slope for robot's shoulder line
    dy_robot = left_shoulder_robot[1] - right_shoulder_robot[1]
    dx_robot = left_shoulder_robot[0] - right_shoulder_robot[0]
    slope_robot = atan2(dy_robot, dx_robot)

    # Calculate angle difference
    angle_diff = abs(degrees(slope_person) - degrees(slope_robot))
    
    # Draw lines for visualization
    draw_line(frame, left_shoulder_person, right_shoulder_person, (0, 255, 0), 2)  # Green line for person
    draw_line(frame, left_shoulder_robot, right_shoulder_robot, (0, 0, 255), 2)    # Red line for robot
    
    return angle_diff < angle_tolerance

# Frame processing
if not os.path.exists(frames_root_directory):
    print("Frames directory does not exist. Please check.")
    exit()

print("Starting frame processing...")
for video_dir in tqdm(os.listdir(frames_root_directory), desc="Processing directories"):
    video_dir_path = os.path.join(frames_root_directory, video_dir)
    
    for frame_file in tqdm(os.listdir(video_dir_path), desc=f"Processing frames in {video_dir}"):
        frame_path = os.path.join(video_dir_path, frame_file)
        frame = cv2.imread(frame_path)
        
        keypoints = model.inference(frame)
        if keypoints:
            latest_person_id = max(keypoints.keys())
            latest_keypoints = keypoints[latest_person_id]

            facing_robot = is_facing_robot(frame, latest_keypoints)
            
            img = model.draw(show_yolo=True)  
            cv2.imshow('image', cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
            cv2.waitKey(0)
            cv2.destroyAllWindows()


`

**Comment by JunkyByte** [comment]
One note, if you add 3 backticks ` ` ` (and 3 to close ` ` `) the code block will appear correctly
```
example
```

----

Your code is fine but has a few errors, the model returns coordinates for keypoints in format `(y, x, score)` while you are using opencv draw line which requires points to be in (x, y, score) format.
Also you are not drawing on the output image. Here's the last corrected part.

```python
print("Starting frame processing...")
for video_dir in tqdm(os.listdir(frames_root_directory), desc="Processing directories"):
    video_dir_path = os.path.join(frames_root_directory, video_dir)
    
    for frame_file in tqdm(os.listdir(video_dir_path), desc=f"Processing frames in {video_dir}"):
        frame_path = os.path.join(video_dir_path, frame_file)
        frame = cv2.imread(frame_path)
        
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        keypoints = model.inference(frame)
        if keypoints:
            latest_person_id = max(keypoints.keys())
            latest_keypoints = keypoints[latest_person_id]
            
            # Switch from (y, x, score) -> (x, y, score)
            latest_keypoints = latest_keypoints[:, [1, 0, 2]]
            # Draw on the frame, as contiguous is required by cv2 here, or copy the image
            img = np.ascontiguousarray(model.draw(show_yolo=True), dtype=np.uint8)
            facing_robot = is_facing_robot(img, latest_keypoints)
            
            cv2.imshow('image', cv2.cvtColor(img, cv2.COLOR_RGB2BGR))
            cv2.waitKey(0)
            cv2.destroyAllWindows()
```

**Comment by sourenpash** [comment]
got it, thank you so much for the help, and thank you for maintaining this package as well.
