### ISSUE TITLE
ModuleNotFoundError: No module named 'easy_ViTPose.vit_models.backbone'

### ISSUE THREAD

**Issue by Yusepp** [JunkyByte/easy_ViTPose#28]
### Description

After updating my local copy of the codebase to the latest version (previously working on a version that was 2 months old), I encountered a `ModuleNotFoundError` during runtime. Specifically, the error points to a missing module within the `easy_ViTPose` package.

### Error Message

```python
ModuleNotFoundError: No module named 'easy_ViTPose.vit_models.backbone'
```

The backbone folder is present within the vit_models directory when I clone the repository directly from GitHub.
However, after installing the package using pip install, the backbone folder does not seem to be included in the installed library.

This issue might be related to how the setup.py is configured, potentially not including the backbone directory during the installation process?

**Comment by JunkyByte** [comment]
Hello @Yusepp. Yes I always installed with `-e` flag and did not notice some `__init__.py` was missing!

Can you try again if it works successfully now? Thank you very much!
