### ISSUE TITLE
Save keypoints

### ISSUE THREAD

**Issue by Priyanshu-Ganwani09** [JunkyByte/easy_ViTPose#39]
**Is there any way to save keypoints like the output formate  given in your directory !**

**Comment by JunkyByte** [comment]
Are you using the `inference.py` script? In that case there’s a flag `—save-json`

**Comment by Priyanshu-Ganwani09** [comment]
I’ve made changes to your notebook, and it’s running smoothly on my system. ViTPose performs exceptionally well on single-channel images, likely due to its efficient architecture, which allows it to effectively adapt to different image formats, including grayscale ?
