### ISSUE TITLE
Error when running the model on videos: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by flopezballent** [JunkyByte/easy_ViTPose#41]
Hello,

Thank you for your amazing work on this project. I am currently facing an issue when trying to run the model on video files. The model works perfectly fine with images, but when I attempt to process a video, I encounter the following error:

![image](https://github.com/user-attachments/assets/6cd5b85a-c74f-4b35-8f80-137b42c30864)

This is the inference i am running:
`!cd easy_ViTPose/ && python inference.py --input /content/Caballo_manga.mp4 --output /content  --model /content/easy_ViTPose/torch/ap10k/vitpose-l-ap10k.pth --yolo /content/easy_ViTPose/yolov8/yolov8n.pt --dataset ap10k --model-name l --yolo-size 320 --save-img`

Could you please provide guidance on how to resolve this issue or confirm if it might be a bug? Let me know if you need more details or logs.

Here is the colab https://colab.research.google.com/drive/1smwjMPXtU8po0Phyca5rbkBClnGML5Vx?usp=sharing

Thank you for your help!

**Comment by JunkyByte** [comment]
Hello! Thank you for the feedback, I pushed an hotfix, could you try again and let me know? Thanks!

**Comment by flopezballent** [comment]
Now it works! thanks, just one comment, the video export format is MP4v, is this a bug or is it the format in which the video is generated as a result?

**Comment by JunkyByte** [comment]
Checking the code the output should be mp4 for videos. But it is taking extension from input file which is not ideal :p. Still it should work in your case

**Comment by JunkyByte** [comment]
Feel free to reopen.

**Comment by flopezballent** [comment]
Hello, now I am having another problem that when I run the inference, it does not store the result, it works with --save-json but not with --save-img.

Here is the fragment where I run the inference and the result that does not throw errors
![image](https://github.com/user-attachments/assets/5b24717b-5098-4a5f-8148-7d516633ed2b)

Here is the notebook  https://colab.research.google.com/drive/1smwjMPXtU8po0Phyca5rbkBClnGML5Vx?usp=sharing

**Comment by JunkyByte** [comment]
Can you try to install ffmpeg on the colab?

`!apt install ffmpeg`

It seems it does not have the h264 codec I set now :(
